version: '3'

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_access
    # TODO: have no need to expose due to web console
    ports:
      - "127.0.0.1:2345:5432"
    env_file:
      - .env

  room_server:
    build: room-server
    depends_on:
      - postgres
    networks:
      - internal
      - db_access
    # Exposes a config reading from env variables sourced below.
    env_file:
      - .env
    volumes:
      - ./config/room-server/config.py:/home/server/config.py
      # Necessary to add new videos.
      - ./config/room-server/eula.txt:/home/server/conf/eula.txt
      - ./assets:/home/server/assets


  food_server:
    build: room-server
    depends_on:
      - postgres
    networks:
      - internal
      - db_access
    # Exposes a config reading from env variables sourced below.
    env_file:
      - .env
    volumes:
      - ./config/food-server/config.py:/home/server/config.py
      - ./food-assets:/home/server/images

  cam_server:
    build: cam-server
    depends_on:
      - postgres
    networks:
      - internal
      - db_access
    env_file:
      - .env
    volumes:
      - ./config/cam-server/config.py:/home/server/config.py
      - ./templates:/home/server/templates
      # Used for order file storage.
      - ./orders:/home/server/orders


  digicard:
    build: Digicard
    depends_on:
      - postgres
      - cam_server
    networks:
      - internal
      - db_access
    env_file:
      - .env
    volumes:
      - ./config/digicard/config.py:/home/server/config.py
      # Used to siphon stashed order file storage.
      - ./orders:/home/server/orders
      - ./cards:/home/server/cards

  nginx:
    build: nginx/
    depends_on:
      - room_server
    networks:
      - internal
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - .env
    volumes:
    - ./assets:/assets
    - ./Digicard:/digicard

networks:
  internal:
  db_access:

volumes:
  pgdata:
