version: '3'

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_access
    # TODO: have no need to expose due to web console
    ports:
      - "127.0.0.1:2345:5432"
    env_file:
      - .env

  elastic:
    build: config/elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic


  room_server:
    build: room-server
    depends_on:
      - postgres
      - elastic
    networks:
      - elastic
      - internal
      - db_access
    # Exposes a config reading from env variables sourced below.
    env_file:
      - .env
    volumes:
      - ./config/room-server/config.py:/home/server/config.py
      # Necessary to add new videos.
      - ./config/room-server/eula.txt:/home/server/conf/eula.txt
      - ./assets:/home/server/assets
      # Necessary for Elasticsearch operation.
      - ./config/elastic/elastic-root-ca-bind.pem:/home/server/conf/elastic-root-ca.pem


  food_server:
    build: food-server
    depends_on:
      - postgres
    networks:
      - internal


  cam_server:
    build: cam-server
    depends_on:
      - postgres
    networks:
      - internal
      - db_access
    env_file:
      - .env
    volumes:
      - ./config/cam-server/config.py:/home/server/config.py
      - ./templates:/home/server/templates
      # Used for order file storage.
      - ./orders:/home/server/orders


  digicard:
    build: Digicard
    depends_on:
      - postgres
      - cam_server
    networks:
      - internal
      - db_access
    env_file:
      - .env
    volumes:
      - ./config/digicard/config.py:/home/server/config.py
      # Used to siphon stashed order file storage.
      - ./orders:/home/server/orders
      - ./cards:/home/server/cards

  nginx:
    build: nginx/
    depends_on:
      - room_server
    networks:
      - internal
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - .env
    volumes:
    - ./assets:/assets
    - ./Digicard:/digicard

networks:
  elastic:
  internal:
  db_access:

volumes:
  esdata:
  pgdata:
