version: '3'

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_access
    # TODO: have no need to expose due to web console
    ports:
      - "127.0.0.1:2345:5432"
    env_file:
      - .env

  elastic:
    image: amazon/opendistro-for-elasticsearch:1.12.0
    environment:
      - node.name=elastic
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic


  room_server:
    build: room-server
    depends_on:
      - postgres
      - elastic
    networks:
      - elastic
      - internal
      - db_access
    # Exposes a config reading from env variables sourced below.
    env_file:
      - .env
    volumes:
      - ./room-server-config/config.py:/home/server/config.py
      # Necessary to add new videos.
      - ./conf/eula.txt:/home/server/conf/eula.txt
      - ./assets:/home/server/assets


  food_server:
    build: food-server
    networks:
      - internal


  cam_server:
    build: cam-server
    depends_on:
      - postgres
    networks:
      - internal
      - db_access
    env_file:
      - .env
    volumes:
      - ./cam-server-config/config.py:/home/server/config.py
      - ./templates:/home/server/templates
      # Used for order file storage.
      - ./orders:/home/server/orders


  nginx:
    build: nginx/
    depends_on:
      - room_server
    networks:
      - internal
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - .env
    volumes:
    - ./assets:/assets

networks:
  elastic:
  internal:
  db_access:

volumes:
  esdata:
  pgdata:
