################################################
# The following is modified from the           #
# official OpenDistro for Elasticsearch image. #
################################################
cluster.name: "elastic"
node.name: "elastic"

bootstrap.memory_lock: true
discovery.type: single-node

network.host: 0.0.0.0

opendistro_security.ssl.transport.pemcert_filepath: elastic-node.pem
opendistro_security.ssl.transport.pemkey_filepath: elastic-node.key
opendistro_security.ssl.transport.pemtrustedcas_filepath: elastic-root-ca.pem

opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: elastic-node.pem
opendistro_security.ssl.http.pemkey_filepath: elastic-node.key
opendistro_security.ssl.http.pemtrustedcas_filepath: elastic-root-ca.pem